#!/usr/bin/env bash
# github.com/trashban/shstatus

# usage: shstatus [interval (seconds)]

__pid=$$        # pid of bar
__bar=""        # bar string displayed/updated
__interval=$1   # base update interval

if [ $# -eq 0 ]; then
    printf '%s\n' "note: interval not specified - defaulting to 1"
    __interval=1
fi

# bar format
## specify modules defined within `modules`
## printed in order (left -> right)
__bar_order=(ipaddr cpu ram vol bat clock)

# modules
## each module uses the following compound keys:
## val - current value of module (your module's function would update it)
## interval - update interval time (seconds)
declare -A modules
modules[ipaddr,interval]=60
modules[cpu,interval]=10
modules[ram,interval]=10
modules[vol,interval]=1
modules[bat,interval]=30
modules[clock,interval]=1

# important: make sure your module name doesn't conflict with existing commands in bash shell!

ipaddr() {
    local res=$(ip -4 addr show up | awk '/inet / && $2 !~ /^127/ {print $2; exit}')
    modules[ipaddr,val]="ip $res"
}

cpu() {
    # sensors provided from `lm-sensors`
    # you might need to adjust `awk` to retrieve the right info
    local res=$(sensors 2>/dev/null | awk '/Package id 0:|Tctl:|temp1:/ {gsub(/\+/, "", $2); print $2; exit}')
    modules[cpu,val]="cpu $res"
}

ram() {
    local res=$(free -h | awk '/^Mem:/ {print $3}')
    modules[ram,val]="ram $res"
}


vol() {
    # assumes pipewire
    local output=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    local res=$(echo "$output" | awk {'print $2 * 100 "%"'})
    if [[ "$output" == *"MUTED"* ]]; then
        res="$res [muted]"
    fi
    modules[vol,val]="vol $res"
}

# example for async updating volume on change (`pipewire-pulse` required for `pactl`)
## on event, this bar ($__pid) is killed with `USR1` which the trap watches and updates
(
    pactl subscribe |
    while read -r event; do
        case "$event" in
            *"sink"*|*"server"*)
                kill -USR1 "$__pid"
                ;;
        esac
    done
) &
trap 'modules[vol,next]=0' SIGUSR1

bat() {
    # change the location of battery according to your device or use `upower`
    local res=$(< /sys/class/power_supply/BAT0/capacity)
    modules[bat,val]="bat: $res%"
}

clock() {
    modules[clock,val]=$(date '+%a %d %H:%M:%S')
}

# by default, the separator prints between each module excluding the first and last modules automatically
# to change this, edit/remove `prevent` in print_bar()
separator() {
    echo " : "
}

# creates and returns status-line as a string composed from modules
update_bar() {
    __bar=""
    local module
    local i

    for i in "${!__bar_order[@]}"; do
        module=${__bar_order[$i]}

        if (( SECONDS >= modules[$module,next] )); then
            "$module"
            modules[$module,next]=$((SECONDS + modules[$module,interval]))
        fi

        __bar+="${modules[$module,val]}"

        # if you want to change the seperator logic, adjust this
        # this currently prints the seperator after the first and before the last module
        if (( i < ${#__bar_order[@]} - 1 )); then
            __bar+="$(separator)"
        fi
    done
}

# you probably don't want to touch this
while true; do
    update_bar
    printf '%s\n' "$__bar"
    sleep "$__interval" &
    wait $!
done
